use_frameworks!

platform :ios, '11.0'

target 'KhrysalisRuntimeInternal_Example' do
  pod 'KhrysalisRuntimeInternal', :path => '../'

  target 'KhrysalisRuntimeInternal_Tests' do
    inherit! :search_paths

    
  end
end
